### ISSUE TITLE
Possibility of endless loop

### ISSUE THREAD

**Issue by kristho91** [danielsen/NetSPF#1]
It is possible to create and endless loop, if a SPF record is wrongly configured.

SPF for a.domain.com:
v=spf1 include:b.domain.com -all

SPF for b.domain.com:
v=spf1 include:a.domain.com -all

Maybe this library could keep track of visited domains, and throw exception/PermError when this happens?

**Comment by danielsen** [comment]
Thanks for the report. I'll check it out.
